genres = {
    "Action": "action",
    "Adventure": "adventure",
    "Animation": "animation",
    "Biography": "biography",
    "Comedy": "comedy",
    "Crime": "crime",
    "Documentary": "documentary",
    "Drama": "drama",
    "Family": "family",
    "Fantasy": "fantasy",
    "Film-Noir": "film_noir",
    "Game-Show": "game_show",
    "History": "history",
    "Horror": "horror",
    "Music": "music",
    "Musical": "musical",
    "Mystery": "mystery",
    "News": "news",
    "Reality-TV": "reality_tv",
    "Romance": "romance",
    "Sci-Fi": "sci_fi",
    "Sport": "sport",
    "Talk-Show": "talk_show",
    "Thriller": "thriller",
    "War": "war",
    "Western": "western",
}
